-- =========================================================
-- Cidade da Arte — Schema do banco de dados (Supabase / Postgres)
-- =========================================================
-- Este arquivo documenta a estrutura da tabela "produtos" e as
-- políticas de acesso (Row Level Security) usadas pelo site.
-- Serve como referência para recriar o banco caso necessário —
-- as políticas abaixo refletem o comportamento já configurado
-- no projeto (leitura pública, escrita só para admins logados).
-- =========================================================

create table if not exists public.produtos (
    id              bigint generated by default as identity primary key,
    nome            text not null,
    categoria       text not null
                        check (categoria in ('Quadros', 'Espelhos')),
    preco           numeric(10,2),   -- usado quando categoria = 'Espelhos'
    preco_quadro    numeric(10,2),   -- usado quando categoria = 'Quadros'
    preco_tela      numeric(10,2),   -- usado quando categoria = 'Quadros'
    tema            text,            -- usado quando categoria = 'Quadros'
    tamanho         text,
    descricao       text,
    imagem_url      text,
    disponibilidade text not null default 'Em estoque'
                        check (disponibilidade in (
                            'Em estoque',
                            'Sob encomenda',
                            'Indisponível'
                        )),
    criado_em       timestamptz not null default now()
);

-- ---------------------------------------------------------
-- ROW LEVEL SECURITY (RLS)
-- ---------------------------------------------------------

alter table public.produtos enable row level security;

-- Qualquer visitante (anônimo) pode LER os produtos —
-- necessário para o catálogo público (quadros.html / espelhos.html)
create policy "Produtos são públicos para leitura"
on public.produtos
for select
using (true);

-- Somente usuários autenticados (administradores) podem
-- inserir novos produtos
create policy "Somente admins autenticados podem inserir"
on public.produtos
for insert
to authenticated
with check (true);

-- Somente usuários autenticados podem atualizar produtos
create policy "Somente admins autenticados podem atualizar"
on public.produtos
for update
to authenticated
using (true);

-- Somente usuários autenticados podem excluir produtos
create policy "Somente admins autenticados podem excluir"
on public.produtos
for delete
to authenticated
using (true);

-- =========================================================
-- STORAGE — bucket "imagens-produtos"
-- =========================================================
-- Configurado manualmente em Storage > New bucket, marcado
-- como PÚBLICO (as imagens precisam carregar no site sem
-- autenticação). Upload e exclusão de arquivos são permitidos
-- apenas para usuários autenticados.
--
-- As políticas de Storage ficam na tabela storage.objects e
-- normalmente são configuradas pela interface do Supabase
-- (Storage > imagens-produtos > Policies). Exemplo equivalente
-- em SQL, caso precise recriar:
-- =========================================================

-- Leitura pública das imagens
create policy "Leitura pública das imagens de produtos"
on storage.objects
for select
using (bucket_id = 'imagens-produtos');

-- Upload somente por usuários autenticados
create policy "Upload de imagens somente por admins"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'imagens-produtos');

-- Exclusão somente por usuários autenticados
create policy "Exclusão de imagens somente por admins"
on storage.objects
for delete
to authenticated
using (bucket_id = 'imagens-produtos');
